version: '3.8'

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: hr-dashboard-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hr_dashboard
      MYSQL_USER: hr_user
      MYSQL_PASSWORD: hr_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./表结构.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - hr-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # HR Dashboard 应用服务
  hr-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr-dashboard-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=hr_dashboard
      - DB_USER=hr_user
      - DB_PASSWORD=hr_password
    volumes:
      - ./uploads:/app/uploads
      - ./excel_templates:/app/excel_templates:ro
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hr-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: hr-dashboard-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - hr-dashboard
    networks:
      - hr-network

volumes:
  mysql_data:
    driver: local

networks:
  hr-network:
    driver: bridge
