-- 人事数据看板数据库结构

-- 创建数据库
CREATE DATABASE IF NOT EXISTS hr_dashboard CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hr_dashboard;

-- 员工花名册表
CREATE TABLE IF NOT EXISTS employee_roster (
  sequence_number VARCHAR(50) COMMENT '序列',
  region VARCHAR(50) COMMENT '区域',
  department VARCHAR(100) COMMENT '部门',
  position VARCHAR(100) COMMENT '岗位',
  name VARCHAR(50) NOT NULL COMMENT '名字',
  gender ENUM('男', '女') COMMENT '性别',
  ethnicity VARCHAR(50) COMMENT '民族',
  political_status VARCHAR(50) COMMENT '政治面貌',
  employee_type VARCHAR(50) COMMENT '员工性质',
  insurance_type VARCHAR(50) COMMENT '险种',
  birth_date DATE COMMENT '出生日期',
  birthday VARCHAR(10) COMMENT '生日',
  entry_date DATE COMMENT '入职时间',
  actual_regularization_date TEXT COMMENT '实际转正日期',
  remarks TEXT COMMENT '备注',
  contract_end_date DATE COMMENT '合同终止日期',
  work_age_months INT COMMENT '工龄（月）',
  id_card_number VARCHAR(18) COMMENT '身份证号',
  id_card_address TEXT COMMENT '身份证地址',
  age INT COMMENT '年龄',
  hometown VARCHAR(100) COMMENT '籍贯',
  graduation_school VARCHAR(200) COMMENT '毕业院校',
  major VARCHAR(100) COMMENT '专业',
  education VARCHAR(50) COMMENT '学历',
  education_method VARCHAR(50) COMMENT '教育方式',
  graduation_date DATE COMMENT '毕业日期',
  interviewer_name VARCHAR(50) COMMENT '面试官姓名',
  marital_status VARCHAR(20) COMMENT '婚姻状况',
  current_address TEXT COMMENT '现居住地',
  personal_contact VARCHAR(50) COMMENT '本人联系方式',
  emergency_contact_name VARCHAR(50) COMMENT '紧急联系人姓名',
  emergency_contact_phone VARCHAR(50) COMMENT '紧急联系人电话',
  bank_card_number VARCHAR(50) COMMENT '银行卡号',
  bank_branch_info TEXT COMMENT '详细支行信息',
  labor_relation_affiliation VARCHAR(100) COMMENT '劳动关系隶属(*)',
  social_insurance_affiliation VARCHAR(100) COMMENT '社保隶属(*)',
  non_compete_agreement VARCHAR(10) COMMENT '竞业协议',
  confidentiality_agreement VARCHAR(10) COMMENT '保密协议',
  remarks1 TEXT COMMENT '备注1',
  remarks2 TEXT COMMENT '备注2',
  organization_region VARCHAR(50) COMMENT '组织区域',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_region (region),
  INDEX idx_department (department),
  INDEX idx_entry_date (entry_date),
  INDEX idx_name (name),
  INDEX idx_organization_region (organization_region)
) COMMENT='员工花名册';

-- 离职监控表
CREATE TABLE IF NOT EXISTS resignation_monitoring (
  id INT PRIMARY KEY AUTO_INCREMENT,
  sequence_number VARCHAR(50) COMMENT '序列',
  region VARCHAR(50) COMMENT '区域',
  department VARCHAR(100) COMMENT '部门',
  position VARCHAR(100) COMMENT '岗位',
  name VARCHAR(50) NOT NULL COMMENT '姓名',
  gender ENUM('男', '女') COMMENT '性别',
  ethnicity VARCHAR(50) COMMENT '民族',
  political_status VARCHAR(50) COMMENT '政治面貌',
  employee_type VARCHAR(50) COMMENT '员工性质',
  insurance_type VARCHAR(50) COMMENT '险种',
  birth_date DATE COMMENT '出生日期',
  birthday VARCHAR(10) COMMENT '生日',
  entry_date DATE COMMENT '入职时间',
  actual_regularization_date TEXT COMMENT '实际转正日期',
  remarks TEXT COMMENT '备注',
  contract_end_date DATE COMMENT '合同终止日期',
  work_age_months INT COMMENT '工龄（月）',
  id_card_number VARCHAR(18) COMMENT '身份证号',
  id_card_address TEXT COMMENT '身份证地址',
  age INT COMMENT '年龄',
  hometown VARCHAR(100) COMMENT '籍贯',
  graduation_school VARCHAR(200) COMMENT '毕业院校',
  major VARCHAR(100) COMMENT '专业',
  education VARCHAR(50) COMMENT '学历',
  education_method VARCHAR(50) COMMENT '教育方式',
  graduation_date TEXT COMMENT '毕业日期',
  interviewer_name VARCHAR(50) COMMENT '面试官姓名',
  marital_status VARCHAR(20) COMMENT '婚姻状况',
  current_address TEXT COMMENT '现居住地',
  personal_contact VARCHAR(50) COMMENT '本人联系方式',
  emergency_contact_name VARCHAR(50) COMMENT '紧急联系人姓名',
  emergency_contact_phone VARCHAR(50) COMMENT '紧急联系人电话',
  bank_card_number VARCHAR(50) COMMENT '银行卡号',
  bank_branch_info TEXT COMMENT '详细支行信息',
  labor_relation_affiliation VARCHAR(100) COMMENT '劳动关系隶属(*)',
  social_insurance_affiliation VARCHAR(100) COMMENT '社保隶属(*)',
  non_compete_agreement VARCHAR(10) COMMENT '竞业协议',
  confidentiality_agreement VARCHAR(10) COMMENT '保密协议',
  resignation_date DATE COMMENT '离职时间',
  resignation_type VARCHAR(50) COMMENT '离职类型',
  resignation_reason TEXT COMMENT '离职原因',
  resignation_remarks TEXT COMMENT '备注',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_region (region),
  INDEX idx_department (department),
  INDEX idx_resignation_date (resignation_date),
  INDEX idx_name (name)
) COMMENT='离职监控表';

-- 人员异动明细表
CREATE TABLE IF NOT EXISTS personnel_changes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  department VARCHAR(100) COMMENT '部门',
  name VARCHAR(50) NOT NULL COMMENT '姓名',
  original_position VARCHAR(100) COMMENT '原岗位',
  new_position VARCHAR(100) COMMENT '新岗位',
  transfer_date DATE COMMENT '异动时间',
  change_reason VARCHAR(100) COMMENT '异动原因（调动/晋升/降职）',
  remarks TEXT COMMENT '备注',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_department (department),
  INDEX idx_name (name),
  INDEX idx_transfer_date (transfer_date)
) COMMENT='人员异动明细表';
