-- 人事数据看板数据库结构 - 严格按照40列字段

-- 创建数据库
CREATE DATABASE IF NOT EXISTS hr_dashboard CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hr_dashboard;

-- 员工花名册表 - 严格按照您提供的40列字段
CREATE TABLE IF NOT EXISTS employee_roster (
  序列 VARCHAR(50),
  区域 VARCHAR(50),
  部门 VARCHAR(100),
  岗位 VARCHAR(100),
  名字 VARCHAR(50) NOT NULL,
  性别 VARCHAR(10),
  民族 VARCHAR(50),
  政治面貌 VARCHAR(50),
  员工性质 VARCHAR(50),
  险种 VARCHAR(50),
  出生日期 DATE,
  生日 VARCHAR(10),
  入职时间 DATE,
  实际转正日期 DATE,
  备注 TEXT,
  合同终止日期 DATE,
  `工龄（月）` INT,
  身份证号 VARCHAR(18),
  身份证地址 TEXT,
  年龄 INT,
  籍贯 VARCHAR(100),
  毕业院校 VARCHAR(200),
  专业 VARCHAR(100),
  学历 VARCHAR(50),
  教育方式 VARCHAR(50),
  毕业日期 DATE,
  面试官姓名 VARCHAR(50),
  婚姻状况 VARCHAR(20),
  现居住地 TEXT,
  本人联系方式 VARCHAR(50),
  紧急联系人姓名 VARCHAR(50),
  紧急联系人电话 VARCHAR(50),
  银行卡号 VARCHAR(50),
  详细支行信息 TEXT,
  `劳动关系隶属(*)` VARCHAR(100),
  `社保隶属(*)` VARCHAR(100),
  竞业协议 VARCHAR(10),
  保密协议 VARCHAR(10),
  备注1 TEXT,
  备注2 TEXT,
  INDEX idx_区域 (区域),
  INDEX idx_部门 (部门),
  INDEX idx_入职时间 (入职时间),
  INDEX idx_名字 (名字)
) COMMENT='员工花名册';

-- 离职监控表 - 在花名册基础上增加离职相关字段
CREATE TABLE IF NOT EXISTS resignation_monitoring (
  序列 VARCHAR(50),
  区域 VARCHAR(50),
  部门 VARCHAR(100),
  岗位 VARCHAR(100),
  姓名 VARCHAR(50) NOT NULL,
  性别 VARCHAR(10),
  民族 VARCHAR(50),
  政治面貌 VARCHAR(50),
  员工性质 VARCHAR(50),
  险种 VARCHAR(50),
  出生日期 DATE,
  生日 VARCHAR(10),
  入职时间 DATE,
  实际转正日期 DATE,
  备注 TEXT,
  合同终止日期 DATE,
  `工龄（月）` INT,
  身份证号 VARCHAR(18),
  身份证地址 TEXT,
  年龄 INT,
  籍贯 VARCHAR(100),
  毕业院校 VARCHAR(200),
  专业 VARCHAR(100),
  学历 VARCHAR(50),
  教育方式 VARCHAR(50),
  毕业日期 DATE,
  面试官姓名 VARCHAR(50),
  婚姻状况 VARCHAR(20),
  现居住地 TEXT,
  本人联系方式 VARCHAR(50),
  紧急联系人姓名 VARCHAR(50),
  紧急联系人电话 VARCHAR(50),
  银行卡号 VARCHAR(50),
  详细支行信息 TEXT,
  `劳动关系隶属(*)` VARCHAR(100),
  `社保隶属(*)` VARCHAR(100),
  竞业协议 VARCHAR(10),
  保密协议 VARCHAR(10),
  备注1 TEXT,
  备注2 TEXT,
  离职时间 DATE,
  离职类型 VARCHAR(50),
  离职原因 TEXT,
  INDEX idx_区域 (区域),
  INDEX idx_部门 (部门),
  INDEX idx_离职时间 (离职时间),
  INDEX idx_姓名 (姓名)
) COMMENT='离职监控表';

-- 人员异动明细表
CREATE TABLE IF NOT EXISTS personnel_changes (
  部门 VARCHAR(100),
  姓名 VARCHAR(50) NOT NULL,
  原岗位 VARCHAR(100),
  新岗位 VARCHAR(100),
  异动时间 DATE,
  `异动原因（调动/晋升/降职）` VARCHAR(100),
  备注 TEXT,
  INDEX idx_部门 (部门),
  INDEX idx_姓名 (姓名),
  INDEX idx_异动时间 (异动时间)
) COMMENT='人员异动明细表';

-- 如果您需要使用英文字段名的版本（便于程序调用），可以使用下面的表结构：

-- 员工花名册表 - 英文字段名版本
CREATE TABLE IF NOT EXISTS employee_roster(
  sequence_number VARCHAR(50),
  region VARCHAR(50),
  department VARCHAR(100),
  position VARCHAR(100),
  name VARCHAR(50) NOT NULL,
  gender VARCHAR(10),
  ethnicity VARCHAR(50),
  political_status VARCHAR(50),
  employee_type VARCHAR(50),
  insurance_type VARCHAR(50),
  birth_date DATE,
  birthday VARCHAR(10),
  entry_date DATE,
  actual_regularization_date DATE,
  remarks TEXT,
  contract_end_date DATE,
  work_age_months INT,
  id_card_number VARCHAR(18),
  id_card_address TEXT,
  age INT,
  hometown VARCHAR(100),
  graduation_school VARCHAR(200),
  major VARCHAR(100),
  education VARCHAR(50),
  education_method VARCHAR(50),
  graduation_date DATE,
  interviewer_name VARCHAR(50),
  marital_status VARCHAR(20),
  current_address TEXT,
  personal_contact VARCHAR(50),
  emergency_contact_name VARCHAR(50),
  emergency_contact_phone VARCHAR(50),
  bank_card_number VARCHAR(50),
  bank_branch_info TEXT,
  labor_relation_affiliation VARCHAR(100),
  social_insurance_affiliation VARCHAR(100),
  non_compete_agreement VARCHAR(10),
  confidentiality_agreement VARCHAR(10),
  remarks1 TEXT,
  remarks2 TEXT,
  INDEX idx_region (region),
  INDEX idx_department (department),
  INDEX idx_entry_date (entry_date),
  INDEX idx_name (name)
) COMMENT='员工花名册-英文字段';

-- 离职监控表 - 英文字段名版本
CREATE TABLE IF NOT EXISTS resignation_monitoring (
  sequence_number VARCHAR(50),
  region VARCHAR(50),
  department VARCHAR(100),
  position VARCHAR(100),
  name VARCHAR(50) NOT NULL,
  gender VARCHAR(10),
  ethnicity VARCHAR(50),
  political_status VARCHAR(50),
  employee_type VARCHAR(50),
  insurance_type VARCHAR(50),
  birth_date DATE,
  birthday VARCHAR(10),
  entry_date DATE,
  actual_regularization_date DATE,
  remarks TEXT,
  contract_end_date DATE,
  work_age_months INT,
  id_card_number VARCHAR(18),
  id_card_address TEXT,
  age INT,
  hometown VARCHAR(100),
  graduation_school VARCHAR(200),
  major VARCHAR(100),
  education VARCHAR(50),
  education_method VARCHAR(50),
  graduation_date DATE,
  interviewer_name VARCHAR(50),
  marital_status VARCHAR(20),
  current_address TEXT,
  personal_contact VARCHAR(50),
  emergency_contact_name VARCHAR(50),
  emergency_contact_phone VARCHAR(50),
  bank_card_number VARCHAR(50),
  bank_branch_info TEXT,
  labor_relation_affiliation VARCHAR(100),
  social_insurance_affiliation VARCHAR(100),
  non_compete_agreement VARCHAR(10),
  confidentiality_agreement VARCHAR(10),
  remarks1 TEXT,
  remarks2 TEXT,
  resignation_date DATE,
  resignation_type VARCHAR(50),
  resignation_reason TEXT,
  INDEX idx_region (region),
  INDEX idx_department (department),
  INDEX idx_resignation_date (resignation_date),
  INDEX idx_name (name)
) COMMENT='离职监控表-英文字段';

-- 人员异动明细表 - 英文字段名版本
CREATE TABLE IF NOT EXISTS personnel_changes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employee_id VARCHAR(50) COMMENT '员工ID，关联花名册',
  department VARCHAR(100) COMMENT '部门',
  name VARCHAR(50) NOT NULL COMMENT '姓名',
  original_position VARCHAR(100) COMMENT '原岗位',
  new_position VARCHAR(100) COMMENT '新岗位',
  change_date DATE COMMENT '异动时间',
  change_type ENUM('调动', '晋升', '降职') COMMENT '异动原因（调动/晋升/降职）',
  change_remarks TEXT COMMENT '备注',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_employee_id (employee_id),
  INDEX idx_department (department),
  INDEX idx_change_date (change_date),
  INDEX idx_name (name)
) COMMENT='人员异动明细表-英文字段';
